// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/proto/cluster_message.proto
// Protobuf Java Version: 4.28.0-rc1

package org.cassell.veikozz.common.entity.message;

public final class ClusterMessage {
  private ClusterMessage() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "-rc1",
      ClusterMessage.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code org.cassell.veikozz.common.entity.message.Direction}
   */
  public enum Direction
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>REQUEST = 0;</code>
     */
    REQUEST(0),
    /**
     * <code>RESPONSE = 1;</code>
     */
    RESPONSE(1),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 0,
        /* suffix= */ "-rc1",
        Direction.class.getName());
    }
    /**
     * <code>REQUEST = 0;</code>
     */
    public static final int REQUEST_VALUE = 0;
    /**
     * <code>RESPONSE = 1;</code>
     */
    public static final int RESPONSE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Direction valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Direction forNumber(int value) {
      switch (value) {
        case 0: return REQUEST;
        case 1: return RESPONSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Direction>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Direction> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Direction>() {
            public Direction findValueByNumber(int number) {
              return Direction.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.cassell.veikozz.common.entity.message.ClusterMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final Direction[] VALUES = values();

    public static Direction valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Direction(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.cassell.veikozz.common.entity.message.Direction)
  }

  /**
   * Protobuf enum {@code org.cassell.veikozz.common.entity.message.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * heartbeat message
     * </pre>
     *
     * <code>HEARTBEAT = 0;</code>
     */
    HEARTBEAT(0),
    /**
     * <pre>
     * collector go online to master message
     * </pre>
     *
     * <code>GO_ONLINE = 1;</code>
     */
    GO_ONLINE(1),
    /**
     * <pre>
     * collector go offline to master message
     * </pre>
     *
     * <code>GO_OFFLINE = 2;</code>
     */
    GO_OFFLINE(2),
    /**
     * <pre>
     * issue cyclic collect task
     * </pre>
     *
     * <code>ISSUE_CYCLIC_TASK = 3;</code>
     */
    ISSUE_CYCLIC_TASK(3),
    /**
     * <pre>
     * delete cyclic collect task
     * </pre>
     *
     * <code>DELETE_CYCLIC_TASK = 4;</code>
     */
    DELETE_CYCLIC_TASK(4),
    /**
     * <pre>
     * issue one-time collect task
     * </pre>
     *
     * <code>ISSUE_ONE_TIME_TASK = 5;</code>
     */
    ISSUE_ONE_TIME_TASK(5),
    /**
     * <pre>
     * response one-time collect data
     * </pre>
     *
     * <code>RESPONSE_ONE_TIME_TASK_DATA = 6;</code>
     */
    RESPONSE_ONE_TIME_TASK_DATA(6),
    /**
     * <pre>
     * response cyclic collect data
     * </pre>
     *
     * <code>RESPONSE_CYCLIC_TASK_DATA = 7;</code>
     */
    RESPONSE_CYCLIC_TASK_DATA(7),
    /**
     * <pre>
     * collector go close to master
     * </pre>
     *
     * <code>GO_CLOSE = 8;</code>
     */
    GO_CLOSE(8),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 0,
        /* suffix= */ "-rc1",
        MessageType.class.getName());
    }
    /**
     * <pre>
     * heartbeat message
     * </pre>
     *
     * <code>HEARTBEAT = 0;</code>
     */
    public static final int HEARTBEAT_VALUE = 0;
    /**
     * <pre>
     * collector go online to master message
     * </pre>
     *
     * <code>GO_ONLINE = 1;</code>
     */
    public static final int GO_ONLINE_VALUE = 1;
    /**
     * <pre>
     * collector go offline to master message
     * </pre>
     *
     * <code>GO_OFFLINE = 2;</code>
     */
    public static final int GO_OFFLINE_VALUE = 2;
    /**
     * <pre>
     * issue cyclic collect task
     * </pre>
     *
     * <code>ISSUE_CYCLIC_TASK = 3;</code>
     */
    public static final int ISSUE_CYCLIC_TASK_VALUE = 3;
    /**
     * <pre>
     * delete cyclic collect task
     * </pre>
     *
     * <code>DELETE_CYCLIC_TASK = 4;</code>
     */
    public static final int DELETE_CYCLIC_TASK_VALUE = 4;
    /**
     * <pre>
     * issue one-time collect task
     * </pre>
     *
     * <code>ISSUE_ONE_TIME_TASK = 5;</code>
     */
    public static final int ISSUE_ONE_TIME_TASK_VALUE = 5;
    /**
     * <pre>
     * response one-time collect data
     * </pre>
     *
     * <code>RESPONSE_ONE_TIME_TASK_DATA = 6;</code>
     */
    public static final int RESPONSE_ONE_TIME_TASK_DATA_VALUE = 6;
    /**
     * <pre>
     * response cyclic collect data
     * </pre>
     *
     * <code>RESPONSE_CYCLIC_TASK_DATA = 7;</code>
     */
    public static final int RESPONSE_CYCLIC_TASK_DATA_VALUE = 7;
    /**
     * <pre>
     * collector go close to master
     * </pre>
     *
     * <code>GO_CLOSE = 8;</code>
     */
    public static final int GO_CLOSE_VALUE = 8;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return HEARTBEAT;
        case 1: return GO_ONLINE;
        case 2: return GO_OFFLINE;
        case 3: return ISSUE_CYCLIC_TASK;
        case 4: return DELETE_CYCLIC_TASK;
        case 5: return ISSUE_ONE_TIME_TASK;
        case 6: return RESPONSE_ONE_TIME_TASK_DATA;
        case 7: return RESPONSE_CYCLIC_TASK_DATA;
        case 8: return GO_CLOSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.cassell.veikozz.common.entity.message.ClusterMessage.getDescriptor().getEnumTypes().get(1);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.cassell.veikozz.common.entity.message.MessageType)
  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.cassell.veikozz.common.entity.message.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * collector id for identifying metrics source
     * </pre>
     *
     * <code>string collectorId = 1;</code>
     * @return The collectorId.
     */
    java.lang.String getCollectorId();
    /**
     * <pre>
     * collector id for identifying metrics source
     * </pre>
     *
     * <code>string collectorId = 1;</code>
     * @return The bytes for collectorId.
     */
    com.google.protobuf.ByteString
        getCollectorIdBytes();

    /**
     * <code>.org.cassell.veikozz.common.entity.message.Direction direction = 2;</code>
     * @return The enum numeric value on the wire for direction.
     */
    int getDirectionValue();
    /**
     * <code>.org.cassell.veikozz.common.entity.message.Direction direction = 2;</code>
     * @return The direction.
     */
    org.cassell.veikozz.common.entity.message.ClusterMessage.Direction getDirection();

    /**
     * <pre>
     * message type
     * </pre>
     *
     * <code>.org.cassell.veikozz.common.entity.message.MessageType type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <pre>
     * message type
     * </pre>
     *
     * <code>.org.cassell.veikozz.common.entity.message.MessageType type = 3;</code>
     * @return The type.
     */
    org.cassell.veikozz.common.entity.message.ClusterMessage.MessageType getType();

    /**
     * <pre>
     * concrete message content
     * </pre>
     *
     * <code>string content = 4;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <pre>
     * concrete message content
     * </pre>
     *
     * <code>string content = 4;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code org.cassell.veikozz.common.entity.message.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.cassell.veikozz.common.entity.message.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 0,
        /* suffix= */ "-rc1",
        Message.class.getName());
    }
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      collectorId_ = "";
      direction_ = 0;
      type_ = 0;
      content_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cassell.veikozz.common.entity.message.ClusterMessage.internal_static_org_cassell_veikozz_common_entity_message_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cassell.veikozz.common.entity.message.ClusterMessage.internal_static_org_cassell_veikozz_common_entity_message_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cassell.veikozz.common.entity.message.ClusterMessage.Message.class, org.cassell.veikozz.common.entity.message.ClusterMessage.Message.Builder.class);
    }

    public static final int COLLECTORID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object collectorId_ = "";
    /**
     * <pre>
     * collector id for identifying metrics source
     * </pre>
     *
     * <code>string collectorId = 1;</code>
     * @return The collectorId.
     */
    @java.lang.Override
    public java.lang.String getCollectorId() {
      java.lang.Object ref = collectorId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        collectorId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * collector id for identifying metrics source
     * </pre>
     *
     * <code>string collectorId = 1;</code>
     * @return The bytes for collectorId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCollectorIdBytes() {
      java.lang.Object ref = collectorId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        collectorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIRECTION_FIELD_NUMBER = 2;
    private int direction_ = 0;
    /**
     * <code>.org.cassell.veikozz.common.entity.message.Direction direction = 2;</code>
     * @return The enum numeric value on the wire for direction.
     */
    @java.lang.Override public int getDirectionValue() {
      return direction_;
    }
    /**
     * <code>.org.cassell.veikozz.common.entity.message.Direction direction = 2;</code>
     * @return The direction.
     */
    @java.lang.Override public org.cassell.veikozz.common.entity.message.ClusterMessage.Direction getDirection() {
      org.cassell.veikozz.common.entity.message.ClusterMessage.Direction result = org.cassell.veikozz.common.entity.message.ClusterMessage.Direction.forNumber(direction_);
      return result == null ? org.cassell.veikozz.common.entity.message.ClusterMessage.Direction.UNRECOGNIZED : result;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_ = 0;
    /**
     * <pre>
     * message type
     * </pre>
     *
     * <code>.org.cassell.veikozz.common.entity.message.MessageType type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * message type
     * </pre>
     *
     * <code>.org.cassell.veikozz.common.entity.message.MessageType type = 3;</code>
     * @return The type.
     */
    @java.lang.Override public org.cassell.veikozz.common.entity.message.ClusterMessage.MessageType getType() {
      org.cassell.veikozz.common.entity.message.ClusterMessage.MessageType result = org.cassell.veikozz.common.entity.message.ClusterMessage.MessageType.forNumber(type_);
      return result == null ? org.cassell.veikozz.common.entity.message.ClusterMessage.MessageType.UNRECOGNIZED : result;
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object content_ = "";
    /**
     * <pre>
     * concrete message content
     * </pre>
     *
     * <code>string content = 4;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * concrete message content
     * </pre>
     *
     * <code>string content = 4;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(collectorId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, collectorId_);
      }
      if (direction_ != org.cassell.veikozz.common.entity.message.ClusterMessage.Direction.REQUEST.getNumber()) {
        output.writeEnum(2, direction_);
      }
      if (type_ != org.cassell.veikozz.common.entity.message.ClusterMessage.MessageType.HEARTBEAT.getNumber()) {
        output.writeEnum(3, type_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, content_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(collectorId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, collectorId_);
      }
      if (direction_ != org.cassell.veikozz.common.entity.message.ClusterMessage.Direction.REQUEST.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, direction_);
      }
      if (type_ != org.cassell.veikozz.common.entity.message.ClusterMessage.MessageType.HEARTBEAT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, content_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.cassell.veikozz.common.entity.message.ClusterMessage.Message)) {
        return super.equals(obj);
      }
      org.cassell.veikozz.common.entity.message.ClusterMessage.Message other = (org.cassell.veikozz.common.entity.message.ClusterMessage.Message) obj;

      if (!getCollectorId()
          .equals(other.getCollectorId())) return false;
      if (direction_ != other.direction_) return false;
      if (type_ != other.type_) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COLLECTORID_FIELD_NUMBER;
      hash = (53 * hash) + getCollectorId().hashCode();
      hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + direction_;
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.cassell.veikozz.common.entity.message.ClusterMessage.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cassell.veikozz.common.entity.message.ClusterMessage.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cassell.veikozz.common.entity.message.ClusterMessage.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cassell.veikozz.common.entity.message.ClusterMessage.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cassell.veikozz.common.entity.message.ClusterMessage.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cassell.veikozz.common.entity.message.ClusterMessage.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cassell.veikozz.common.entity.message.ClusterMessage.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.cassell.veikozz.common.entity.message.ClusterMessage.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.cassell.veikozz.common.entity.message.ClusterMessage.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.cassell.veikozz.common.entity.message.ClusterMessage.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cassell.veikozz.common.entity.message.ClusterMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.cassell.veikozz.common.entity.message.ClusterMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.cassell.veikozz.common.entity.message.ClusterMessage.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.cassell.veikozz.common.entity.message.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.cassell.veikozz.common.entity.message.Message)
        org.cassell.veikozz.common.entity.message.ClusterMessage.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cassell.veikozz.common.entity.message.ClusterMessage.internal_static_org_cassell_veikozz_common_entity_message_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cassell.veikozz.common.entity.message.ClusterMessage.internal_static_org_cassell_veikozz_common_entity_message_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cassell.veikozz.common.entity.message.ClusterMessage.Message.class, org.cassell.veikozz.common.entity.message.ClusterMessage.Message.Builder.class);
      }

      // Construct using org.cassell.veikozz.common.entity.message.ClusterMessage.Message.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        collectorId_ = "";
        direction_ = 0;
        type_ = 0;
        content_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cassell.veikozz.common.entity.message.ClusterMessage.internal_static_org_cassell_veikozz_common_entity_message_Message_descriptor;
      }

      @java.lang.Override
      public org.cassell.veikozz.common.entity.message.ClusterMessage.Message getDefaultInstanceForType() {
        return org.cassell.veikozz.common.entity.message.ClusterMessage.Message.getDefaultInstance();
      }

      @java.lang.Override
      public org.cassell.veikozz.common.entity.message.ClusterMessage.Message build() {
        org.cassell.veikozz.common.entity.message.ClusterMessage.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.cassell.veikozz.common.entity.message.ClusterMessage.Message buildPartial() {
        org.cassell.veikozz.common.entity.message.ClusterMessage.Message result = new org.cassell.veikozz.common.entity.message.ClusterMessage.Message(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.cassell.veikozz.common.entity.message.ClusterMessage.Message result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.collectorId_ = collectorId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.direction_ = direction_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.content_ = content_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cassell.veikozz.common.entity.message.ClusterMessage.Message) {
          return mergeFrom((org.cassell.veikozz.common.entity.message.ClusterMessage.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cassell.veikozz.common.entity.message.ClusterMessage.Message other) {
        if (other == org.cassell.veikozz.common.entity.message.ClusterMessage.Message.getDefaultInstance()) return this;
        if (!other.getCollectorId().isEmpty()) {
          collectorId_ = other.collectorId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.direction_ != 0) {
          setDirectionValue(other.getDirectionValue());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                collectorId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                direction_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                content_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object collectorId_ = "";
      /**
       * <pre>
       * collector id for identifying metrics source
       * </pre>
       *
       * <code>string collectorId = 1;</code>
       * @return The collectorId.
       */
      public java.lang.String getCollectorId() {
        java.lang.Object ref = collectorId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          collectorId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * collector id for identifying metrics source
       * </pre>
       *
       * <code>string collectorId = 1;</code>
       * @return The bytes for collectorId.
       */
      public com.google.protobuf.ByteString
          getCollectorIdBytes() {
        java.lang.Object ref = collectorId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          collectorId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * collector id for identifying metrics source
       * </pre>
       *
       * <code>string collectorId = 1;</code>
       * @param value The collectorId to set.
       * @return This builder for chaining.
       */
      public Builder setCollectorId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        collectorId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * collector id for identifying metrics source
       * </pre>
       *
       * <code>string collectorId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCollectorId() {
        collectorId_ = getDefaultInstance().getCollectorId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * collector id for identifying metrics source
       * </pre>
       *
       * <code>string collectorId = 1;</code>
       * @param value The bytes for collectorId to set.
       * @return This builder for chaining.
       */
      public Builder setCollectorIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        collectorId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int direction_ = 0;
      /**
       * <code>.org.cassell.veikozz.common.entity.message.Direction direction = 2;</code>
       * @return The enum numeric value on the wire for direction.
       */
      @java.lang.Override public int getDirectionValue() {
        return direction_;
      }
      /**
       * <code>.org.cassell.veikozz.common.entity.message.Direction direction = 2;</code>
       * @param value The enum numeric value on the wire for direction to set.
       * @return This builder for chaining.
       */
      public Builder setDirectionValue(int value) {
        direction_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.org.cassell.veikozz.common.entity.message.Direction direction = 2;</code>
       * @return The direction.
       */
      @java.lang.Override
      public org.cassell.veikozz.common.entity.message.ClusterMessage.Direction getDirection() {
        org.cassell.veikozz.common.entity.message.ClusterMessage.Direction result = org.cassell.veikozz.common.entity.message.ClusterMessage.Direction.forNumber(direction_);
        return result == null ? org.cassell.veikozz.common.entity.message.ClusterMessage.Direction.UNRECOGNIZED : result;
      }
      /**
       * <code>.org.cassell.veikozz.common.entity.message.Direction direction = 2;</code>
       * @param value The direction to set.
       * @return This builder for chaining.
       */
      public Builder setDirection(org.cassell.veikozz.common.entity.message.ClusterMessage.Direction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        direction_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.org.cassell.veikozz.common.entity.message.Direction direction = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDirection() {
        bitField0_ = (bitField0_ & ~0x00000002);
        direction_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * message type
       * </pre>
       *
       * <code>.org.cassell.veikozz.common.entity.message.MessageType type = 3;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * message type
       * </pre>
       *
       * <code>.org.cassell.veikozz.common.entity.message.MessageType type = 3;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * message type
       * </pre>
       *
       * <code>.org.cassell.veikozz.common.entity.message.MessageType type = 3;</code>
       * @return The type.
       */
      @java.lang.Override
      public org.cassell.veikozz.common.entity.message.ClusterMessage.MessageType getType() {
        org.cassell.veikozz.common.entity.message.ClusterMessage.MessageType result = org.cassell.veikozz.common.entity.message.ClusterMessage.MessageType.forNumber(type_);
        return result == null ? org.cassell.veikozz.common.entity.message.ClusterMessage.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * message type
       * </pre>
       *
       * <code>.org.cassell.veikozz.common.entity.message.MessageType type = 3;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(org.cassell.veikozz.common.entity.message.ClusterMessage.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * message type
       * </pre>
       *
       * <code>.org.cassell.veikozz.common.entity.message.MessageType type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       * concrete message content
       * </pre>
       *
       * <code>string content = 4;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * concrete message content
       * </pre>
       *
       * <code>string content = 4;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * concrete message content
       * </pre>
       *
       * <code>string content = 4;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        content_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * concrete message content
       * </pre>
       *
       * <code>string content = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        content_ = getDefaultInstance().getContent();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * concrete message content
       * </pre>
       *
       * <code>string content = 4;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        content_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.cassell.veikozz.common.entity.message.Message)
    }

    // @@protoc_insertion_point(class_scope:org.cassell.veikozz.common.entity.message.Message)
    private static final org.cassell.veikozz.common.entity.message.ClusterMessage.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.cassell.veikozz.common.entity.message.ClusterMessage.Message();
    }

    public static org.cassell.veikozz.common.entity.message.ClusterMessage.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.cassell.veikozz.common.entity.message.ClusterMessage.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_cassell_veikozz_common_entity_message_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_cassell_veikozz_common_entity_message_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.src/main/resources/proto/cluster_messa" +
      "ge.proto\022)org.cassell.veikozz.common.ent" +
      "ity.message\"\276\001\n\007Message\022\023\n\013collectorId\030\001" +
      " \001(\t\022G\n\tdirection\030\002 \001(\01624.org.cassell.ve" +
      "ikozz.common.entity.message.Direction\022D\n" +
      "\004type\030\003 \001(\01626.org.cassell.veikozz.common" +
      ".entity.message.MessageType\022\017\n\007content\030\004" +
      " \001(\t*&\n\tDirection\022\013\n\007REQUEST\020\000\022\014\n\010RESPON" +
      "SE\020\001*\321\001\n\013MessageType\022\r\n\tHEARTBEAT\020\000\022\r\n\tG" +
      "O_ONLINE\020\001\022\016\n\nGO_OFFLINE\020\002\022\025\n\021ISSUE_CYCL" +
      "IC_TASK\020\003\022\026\n\022DELETE_CYCLIC_TASK\020\004\022\027\n\023ISS" +
      "UE_ONE_TIME_TASK\020\005\022\037\n\033RESPONSE_ONE_TIME_" +
      "TASK_DATA\020\006\022\035\n\031RESPONSE_CYCLIC_TASK_DATA" +
      "\020\007\022\014\n\010GO_CLOSE\020\010b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_cassell_veikozz_common_entity_message_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_cassell_veikozz_common_entity_message_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_cassell_veikozz_common_entity_message_Message_descriptor,
        new java.lang.String[] { "CollectorId", "Direction", "Type", "Content", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
